[2023-01-25T19:03:54.562+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [queued]>
[2023-01-25T19:03:54.613+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [queued]>
[2023-01-25T19:03:54.615+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:03:54.617+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-25T19:03:54.620+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:03:54.680+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-27 00:00:00+00:00
[2023-01-25T19:03:54.698+0000] {standard_task_runner.py:55} INFO - Started process 3151 to run task
[2023-01-25T19:03:54.709+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-27T00:00:00+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpkswkfe05']
[2023-01-25T19:03:54.712+0000] {standard_task_runner.py:83} INFO - Job 330: Subtask complete_twitter_etl
[2023-01-25T19:03:54.883+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [running]> on host 512d0ff0785b
[2023-01-25T19:03:55.538+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-27T00:00:00+00:00
[2023-01-25T19:04:01.448+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Anonymous access is forbidden for this operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitter_etl.py", line 46, in run_twitter_etl
    df.to_csv("s3://jinchoi-airflow-bucket/data/elonmusk_tweets.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 370, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 428, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 883, in _makedirs
    await self._mkdir(path, create_parents=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 868, in _mkdir
    await self._call_s3("create_bucket", **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 340, in _call_s3
    method, kwargs=additional_kwargs, retries=self.retries
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
PermissionError: Anonymous access is forbidden for this operation
[2023-01-25T19:04:01.495+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210427T000000, start_date=20230125T190354, end_date=20230125T190401
[2023-01-25T19:04:01.778+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 330 for task complete_twitter_etl (Anonymous access is forbidden for this operation; 3151)
[2023-01-25T19:04:01.867+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-25T19:04:01.916+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T07:14:49.847+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [queued]>
[2023-01-26T07:14:50.022+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [queued]>
[2023-01-26T07:14:50.045+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:14:50.048+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T07:14:50.054+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:14:50.230+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-27 00:00:00+00:00
[2023-01-26T07:14:50.334+0000] {standard_task_runner.py:55} INFO - Started process 1481 to run task
[2023-01-26T07:14:50.356+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-27T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpvykzf49f']
[2023-01-26T07:14:50.374+0000] {standard_task_runner.py:83} INFO - Job 208: Subtask complete_twitter_etl
[2023-01-26T07:14:51.742+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [running]> on host 2221c1ebf970
[2023-01-26T07:14:52.130+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-27T00:00:00+00:00
[2023-01-26T07:14:53.815+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T07:14:53.897+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210427T000000, start_date=20230126T071449, end_date=20230126T071453
[2023-01-26T07:14:54.469+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T07:14:54.630+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T09:12:50.399+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [queued]>
[2023-01-26T09:12:50.427+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [queued]>
[2023-01-26T09:12:50.433+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T09:12:50.435+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T09:12:50.438+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T09:12:50.485+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-27 00:00:00+00:00
[2023-01-26T09:12:50.505+0000] {standard_task_runner.py:55} INFO - Started process 815 to run task
[2023-01-26T09:12:50.516+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-27T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp7q247my3']
[2023-01-26T09:12:50.518+0000] {standard_task_runner.py:83} INFO - Job 173: Subtask complete_twitter_etl
[2023-01-26T09:12:51.081+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-27T00:00:00+00:00 [running]> on host d0fc3b00c15c
[2023-01-26T09:12:51.216+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-27T00:00:00+00:00
[2023-01-26T09:15:22.398+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T09:15:22.533+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210427T000000, start_date=20230126T091250, end_date=20230126T091522
[2023-01-26T09:15:23.593+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T09:15:24.912+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
