[2023-01-25T19:12:34.841+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2023-01-25T19:12:34.983+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2023-01-25T19:12:34.986+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:12:34.987+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-25T19:12:34.989+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:12:35.316+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-07-01 00:00:00+00:00
[2023-01-25T19:12:35.394+0000] {standard_task_runner.py:55} INFO - Started process 4258 to run task
[2023-01-25T19:12:35.442+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '462', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpj9jmcsfc']
[2023-01-25T19:12:35.450+0000] {standard_task_runner.py:83} INFO - Job 462: Subtask complete_twitter_etl
[2023-01-25T19:12:35.812+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-07-01T00:00:00+00:00 [running]> on host 512d0ff0785b
[2023-01-25T19:12:36.524+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2023-01-25T19:12:42.188+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Anonymous access is forbidden for this operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitter_etl.py", line 46, in run_twitter_etl
    df.to_csv("s3://jinchoi-airflow-bucket/data/elonmusk_tweets.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 370, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 428, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 883, in _makedirs
    await self._mkdir(path, create_parents=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 868, in _mkdir
    await self._call_s3("create_bucket", **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 340, in _call_s3
    method, kwargs=additional_kwargs, retries=self.retries
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
PermissionError: Anonymous access is forbidden for this operation
[2023-01-25T19:12:42.236+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210701T000000, start_date=20230125T191234, end_date=20230125T191242
[2023-01-25T19:12:42.277+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 462 for task complete_twitter_etl (Anonymous access is forbidden for this operation; 4258)
[2023-01-25T19:12:42.341+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-25T19:12:42.371+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T07:16:29.210+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2023-01-26T07:16:29.322+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2023-01-26T07:16:29.323+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:16:29.328+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T07:16:29.332+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:16:30.323+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-07-01 00:00:00+00:00
[2023-01-26T07:16:30.346+0000] {standard_task_runner.py:55} INFO - Started process 1757 to run task
[2023-01-26T07:16:30.364+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpqawk2pms']
[2023-01-26T07:16:30.382+0000] {standard_task_runner.py:83} INFO - Job 275: Subtask complete_twitter_etl
[2023-01-26T07:16:30.839+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-07-01T00:00:00+00:00 [running]> on host 2221c1ebf970
[2023-01-26T07:16:31.503+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2023-01-26T07:16:39.458+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T07:16:39.527+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210701T000000, start_date=20230126T071629, end_date=20230126T071639
[2023-01-26T07:16:40.592+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T07:16:40.767+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
