[2023-01-25T19:01:31.892+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-01-25T19:01:32.178+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-01-25T19:01:32.183+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:01:32.202+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-25T19:01:32.210+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:01:32.454+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-11 00:00:00+00:00
[2023-01-25T19:01:32.569+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpvecusro_']
[2023-01-25T19:01:32.573+0000] {standard_task_runner.py:83} INFO - Job 297: Subtask complete_twitter_etl
[2023-01-25T19:01:32.556+0000] {standard_task_runner.py:55} INFO - Started process 2839 to run task
[2023-01-25T19:01:33.586+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [running]> on host 512d0ff0785b
[2023-01-25T19:01:34.935+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-11T00:00:00+00:00
[2023-01-25T19:01:42.364+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Anonymous access is forbidden for this operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitter_etl.py", line 46, in run_twitter_etl
    df.to_csv("s3://jinchoi-airflow-bucket/data/elonmusk_tweets.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 370, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 428, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 883, in _makedirs
    await self._mkdir(path, create_parents=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 868, in _mkdir
    await self._call_s3("create_bucket", **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 340, in _call_s3
    method, kwargs=additional_kwargs, retries=self.retries
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
PermissionError: Anonymous access is forbidden for this operation
[2023-01-25T19:01:42.407+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210411T000000, start_date=20230125T190131, end_date=20230125T190142
[2023-01-25T19:01:42.443+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 297 for task complete_twitter_etl (Anonymous access is forbidden for this operation; 2839)
[2023-01-25T19:01:42.535+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-25T19:01:42.578+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T07:14:29.383+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-01-26T07:14:29.461+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-01-26T07:14:29.468+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:14:29.473+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T07:14:29.481+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:14:29.593+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-11 00:00:00+00:00
[2023-01-26T07:14:29.660+0000] {standard_task_runner.py:55} INFO - Started process 1423 to run task
[2023-01-26T07:14:29.717+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpoy42zj6x']
[2023-01-26T07:14:29.723+0000] {standard_task_runner.py:83} INFO - Job 194: Subtask complete_twitter_etl
[2023-01-26T07:14:31.978+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [running]> on host 2221c1ebf970
[2023-01-26T07:14:32.998+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-11T00:00:00+00:00
[2023-01-26T07:14:35.310+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T07:14:35.361+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210411T000000, start_date=20230126T071429, end_date=20230126T071435
[2023-01-26T07:14:35.679+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T07:14:36.805+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T09:12:23.315+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-01-26T09:12:23.513+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-01-26T09:12:23.519+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T09:12:23.523+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T09:12:23.530+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T09:12:24.001+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-04-11 00:00:00+00:00
[2023-01-26T09:12:24.097+0000] {standard_task_runner.py:55} INFO - Started process 766 to run task
[2023-01-26T09:12:24.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpa50p017g']
[2023-01-26T09:12:24.227+0000] {standard_task_runner.py:83} INFO - Job 156: Subtask complete_twitter_etl
[2023-01-26T09:12:28.065+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-04-11T00:00:00+00:00 [running]> on host d0fc3b00c15c
[2023-01-26T09:12:28.792+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-04-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-11T00:00:00+00:00
[2023-01-26T09:12:31.740+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T09:12:31.774+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210411T000000, start_date=20230126T091223, end_date=20230126T091231
[2023-01-26T09:12:31.984+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T09:12:33.744+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
