[2023-01-24T08:01:30.319+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:01:30.322+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:01:30.323+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:01:30.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:01:30.366+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:01:30.362+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:01:30.367+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:01:30.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.102 seconds
[2023-01-24T08:02:01.302+0000] {processor.py:153} INFO - Started process (PID=97) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:02:01.305+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:02:01.307+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:02:01.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:02:01.329+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:02:01.326+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:02:01.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:02:01.356+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T08:02:32.171+0000] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:02:32.173+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:02:32.174+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:02:32.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:02:32.194+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:02:32.191+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:02:32.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:02:32.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.063 seconds
[2023-01-24T08:03:02.966+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:03:02.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:03:02.971+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:03:02.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:03:02.989+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:03:02.985+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:03:02.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:03:03.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.055 seconds
[2023-01-24T08:03:33.216+0000] {processor.py:153} INFO - Started process (PID=303) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:03:33.219+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:03:33.221+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:03:33.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:03:33.237+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:03:33.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:03:33.238+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:03:33.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.054 seconds
[2023-01-24T08:04:03.681+0000] {processor.py:153} INFO - Started process (PID=379) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:04:03.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:04:03.686+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:04:03.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:04:03.702+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:04:03.699+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:04:03.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:04:03.728+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.053 seconds
[2023-01-24T08:04:34.156+0000] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:04:34.158+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:04:34.160+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:04:34.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:04:34.182+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:04:34.174+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:04:34.184+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:04:34.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.074 seconds
[2023-01-24T08:05:04.765+0000] {processor.py:153} INFO - Started process (PID=516) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:05:04.769+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:05:04.770+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:05:04.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:05:04.793+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:05:04.788+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:05:04.796+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:05:04.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.066 seconds
[2023-01-24T08:05:35.091+0000] {processor.py:153} INFO - Started process (PID=583) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:05:35.094+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:05:35.096+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:05:35.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:05:35.114+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:05:35.111+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:05:35.116+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:05:35.142+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.057 seconds
[2023-01-24T08:06:05.868+0000] {processor.py:153} INFO - Started process (PID=648) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:06:05.871+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:06:05.874+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:06:05.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:06:05.896+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:06:05.890+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:06:05.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:06:05.949+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.087 seconds
[2023-01-24T08:06:36.667+0000] {processor.py:153} INFO - Started process (PID=722) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:06:36.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:06:36.682+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:06:36.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:06:36.733+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:06:36.717+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:06:36.737+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:06:36.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.159 seconds
[2023-01-24T08:07:07.237+0000] {processor.py:153} INFO - Started process (PID=790) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:07:07.240+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:07:07.242+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:07:07.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:07:07.266+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:07:07.261+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:07:07.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:07:07.297+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.065 seconds
[2023-01-24T08:07:38.218+0000] {processor.py:153} INFO - Started process (PID=855) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:07:38.229+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:07:38.237+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:07:38.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:07:38.267+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:07:38.263+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:07:38.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:07:38.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.098 seconds
[2023-01-24T08:09:49.000+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:09:49.009+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:09:49.015+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:09:49.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:09:49.088+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:09:49.082+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:09:49.090+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:09:49.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.189 seconds
[2023-01-24T08:10:19.922+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:10:19.925+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:10:19.927+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:10:19.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:10:19.947+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:10:19.943+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:10:19.952+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:10:19.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.065 seconds
[2023-01-24T08:10:50.032+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:10:50.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:10:50.036+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:10:50.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:10:50.053+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:10:50.050+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:10:50.054+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:10:50.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.066 seconds
[2023-01-24T08:11:20.501+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:11:20.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:11:20.512+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:11:20.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:11:20.539+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:11:20.535+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:11:20.540+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:11:20.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.082 seconds
[2023-01-24T08:11:51.407+0000] {processor.py:153} INFO - Started process (PID=316) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:11:51.410+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:11:51.412+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:11:51.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:11:51.428+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:11:51.425+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:11:51.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:11:51.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.056 seconds
[2023-01-24T08:12:22.075+0000] {processor.py:153} INFO - Started process (PID=381) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:12:22.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:12:22.084+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:12:22.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:12:22.127+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:12:22.114+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:12:22.130+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:12:22.212+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.142 seconds
[2023-01-24T08:12:52.617+0000] {processor.py:153} INFO - Started process (PID=457) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:12:52.620+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:12:52.622+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:12:52.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:12:52.637+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:12:52.634+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:12:52.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:12:52.666+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.056 seconds
[2023-01-24T08:13:23.527+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:13:23.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:13:23.531+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:13:23.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:13:23.545+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:13:23.542+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:13:23.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:13:23.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.052 seconds
[2023-01-24T08:13:54.306+0000] {processor.py:153} INFO - Started process (PID=599) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:13:54.312+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:13:54.316+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:13:54.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:13:54.340+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:13:54.335+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:13:54.342+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:13:54.386+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.095 seconds
[2023-01-24T08:14:25.189+0000] {processor.py:153} INFO - Started process (PID=663) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:14:25.192+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:14:25.194+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:14:25.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:14:25.213+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:14:25.210+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:14:25.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:14:25.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.063 seconds
[2023-01-24T08:14:56.211+0000] {processor.py:153} INFO - Started process (PID=734) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:14:56.215+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:14:56.216+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:14:56.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:14:56.244+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:14:56.239+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:14:56.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:14:56.292+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.086 seconds
[2023-01-24T08:15:26.874+0000] {processor.py:153} INFO - Started process (PID=804) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:15:26.878+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:15:26.880+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:15:26.880+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:15:26.898+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:15:26.895+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:15:26.899+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:15:26.924+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.057 seconds
[2023-01-24T08:15:57.477+0000] {processor.py:153} INFO - Started process (PID=868) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:15:57.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:15:57.481+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:15:57.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:15:57.497+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:15:57.493+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:15:57.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:15:57.523+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.053 seconds
[2023-01-24T08:16:28.040+0000] {processor.py:153} INFO - Started process (PID=945) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:16:28.043+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:16:28.045+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:16:28.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:16:28.063+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:16:28.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:16:28.064+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:16:28.093+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.057 seconds
[2023-01-24T08:18:17.049+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:18:17.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:18:17.073+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:18:17.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:18:17.174+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:18:17.154+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:18:17.175+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:18:17.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.257 seconds
[2023-01-24T08:18:47.751+0000] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:18:47.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:18:47.757+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:18:47.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:18:47.773+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:18:47.770+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:18:47.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:18:47.799+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.055 seconds
[2023-01-24T08:19:18.669+0000] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:19:18.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:19:18.673+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:19:18.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:19:18.689+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:19:18.686+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:19:18.691+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:19:18.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.059 seconds
[2023-01-24T08:19:49.483+0000] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:19:49.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:19:49.487+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:19:49.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:19:49.501+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:19:49.499+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:19:49.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:19:49.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.050 seconds
[2023-01-24T08:20:19.721+0000] {processor.py:153} INFO - Started process (PID=313) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:20:19.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:20:19.726+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:20:19.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:20:19.740+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:20:19.737+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:20:19.741+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:20:19.768+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.055 seconds
[2023-01-24T08:20:50.621+0000] {processor.py:153} INFO - Started process (PID=378) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:20:50.625+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:20:50.628+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:20:50.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:20:50.657+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:20:50.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:20:50.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:20:50.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.077 seconds
[2023-01-24T08:21:21.149+0000] {processor.py:153} INFO - Started process (PID=456) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:21:21.152+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:21:21.154+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:21:21.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:21:21.169+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:21:21.166+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:21:21.170+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:21:21.194+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.054 seconds
[2023-01-24T08:21:51.651+0000] {processor.py:153} INFO - Started process (PID=520) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:21:51.656+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:21:51.660+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:21:51.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:21:51.683+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:21:51.678+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:21:51.684+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:21:51.720+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.074 seconds
[2023-01-24T08:22:21.927+0000] {processor.py:153} INFO - Started process (PID=596) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:22:21.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:22:21.933+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:22:21.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:22:21.954+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:22:21.948+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:22:21.956+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:22:21.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.071 seconds
[2023-01-24T08:22:52.814+0000] {processor.py:153} INFO - Started process (PID=660) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:22:52.817+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:22:52.818+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:22:52.818+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:22:52.833+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:22:52.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:22:52.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:22:52.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.054 seconds
[2023-01-24T08:23:23.421+0000] {processor.py:153} INFO - Started process (PID=723) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:23:23.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T08:23:23.426+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:23:23.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:23:23.444+0000] {logging_mixin.py:137} INFO - [2023-01-24T08:23:23.441+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T08:23:23.445+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T08:23:23.473+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.057 seconds
[2023-01-24T19:52:25.310+0000] {processor.py:153} INFO - Started process (PID=788) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:52:25.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:52:25.326+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:52:25.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:52:25.414+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:52:25.404+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:52:25.417+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:52:25.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.190 seconds
[2023-01-24T19:56:10.927+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:56:10.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:56:10.937+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:56:10.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:56:10.979+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:56:10.968+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:56:10.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:56:11.031+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.112 seconds
[2023-01-24T19:56:41.222+0000] {processor.py:153} INFO - Started process (PID=97) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:56:41.225+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:56:41.227+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:56:41.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:56:41.247+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:56:41.243+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:56:41.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:56:41.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T19:57:11.692+0000] {processor.py:153} INFO - Started process (PID=161) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:57:11.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:57:11.699+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:57:11.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:57:11.717+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:57:11.713+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:57:11.719+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:57:11.751+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.066 seconds
[2023-01-24T19:57:42.045+0000] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:57:42.054+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:57:42.058+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:57:42.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:57:42.108+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:57:42.100+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:57:42.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:57:42.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.135 seconds
[2023-01-24T19:58:12.863+0000] {processor.py:153} INFO - Started process (PID=303) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:58:12.867+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:58:12.870+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:58:12.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:58:12.891+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:58:12.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:58:12.893+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:58:12.935+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.078 seconds
[2023-01-24T19:58:43.301+0000] {processor.py:153} INFO - Started process (PID=367) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:58:43.305+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:58:43.307+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:58:43.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:58:43.339+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:58:43.332+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:58:43.341+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:58:43.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.085 seconds
[2023-01-24T19:59:13.641+0000] {processor.py:153} INFO - Started process (PID=431) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:59:13.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:59:13.663+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:59:13.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:59:13.726+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:59:13.713+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:59:13.730+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:59:13.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.180 seconds
[2023-01-24T19:59:44.206+0000] {processor.py:153} INFO - Started process (PID=495) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:59:44.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T19:59:44.213+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:59:44.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:59:44.237+0000] {logging_mixin.py:137} INFO - [2023-01-24T19:59:44.229+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T19:59:44.239+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T19:59:44.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.091 seconds
[2023-01-24T20:13:23.774+0000] {processor.py:153} INFO - Started process (PID=511) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:13:23.806+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:13:23.814+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:13:23.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:13:23.925+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:13:23.912+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:13:23.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:13:23.994+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.295 seconds
[2023-01-24T20:13:54.577+0000] {processor.py:153} INFO - Started process (PID=579) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:13:54.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:13:54.591+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:13:54.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:13:54.634+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:13:54.627+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:13:54.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:13:54.698+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.139 seconds
[2023-01-24T20:14:25.594+0000] {processor.py:153} INFO - Started process (PID=643) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:14:25.601+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:14:25.606+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:14:25.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:14:25.639+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:14:25.632+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:14:25.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:14:25.680+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.096 seconds
[2023-01-24T20:14:55.895+0000] {processor.py:153} INFO - Started process (PID=706) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:14:55.898+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:14:55.900+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:14:55.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:14:55.919+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:14:55.915+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:14:55.921+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:14:55.956+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.067 seconds
[2023-01-24T20:15:26.797+0000] {processor.py:153} INFO - Started process (PID=770) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:15:26.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:15:26.802+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:15:26.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:15:26.823+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:15:26.819+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:15:26.824+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:15:26.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.067 seconds
[2023-01-24T20:15:56.898+0000] {processor.py:153} INFO - Started process (PID=834) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:15:56.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:15:56.903+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:15:56.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:15:56.923+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:15:56.918+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:15:56.926+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:15:56.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.069 seconds
[2023-01-24T20:16:27.571+0000] {processor.py:153} INFO - Started process (PID=906) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:16:27.575+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:16:27.579+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:16:27.578+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:16:27.621+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:16:27.605+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:16:27.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:16:27.671+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.110 seconds
[2023-01-24T20:16:57.763+0000] {processor.py:153} INFO - Started process (PID=973) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:16:57.769+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:16:57.773+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:16:57.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:16:57.811+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:16:57.805+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:16:57.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:16:57.894+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.145 seconds
[2023-01-24T20:17:28.607+0000] {processor.py:153} INFO - Started process (PID=1037) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:17:28.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:17:28.612+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:17:28.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:17:28.634+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:17:28.629+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:17:28.636+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:17:28.668+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.067 seconds
[2023-01-24T20:17:58.984+0000] {processor.py:153} INFO - Started process (PID=1102) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:17:58.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:17:58.992+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:17:58.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:17:59.021+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:17:59.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:17:59.022+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:17:59.053+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.083 seconds
[2023-01-24T20:18:29.937+0000] {processor.py:153} INFO - Started process (PID=1178) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:18:29.942+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:18:29.946+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:18:29.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:18:29.978+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:18:29.971+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:18:29.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:18:30.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.101 seconds
[2023-01-24T20:19:00.275+0000] {processor.py:153} INFO - Started process (PID=1242) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:19:00.279+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:19:00.282+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:19:00.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:19:00.325+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:19:00.315+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:19:00.329+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:19:00.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.100 seconds
[2023-01-24T20:19:30.883+0000] {processor.py:153} INFO - Started process (PID=1307) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:19:30.886+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:19:30.889+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:19:30.888+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:19:30.935+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:19:30.931+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:19:30.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:19:30.970+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.093 seconds
[2023-01-24T20:20:01.218+0000] {processor.py:153} INFO - Started process (PID=1373) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:20:01.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:20:01.226+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:20:01.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:20:01.255+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:20:01.250+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:20:01.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:20:01.316+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.106 seconds
[2023-01-24T20:20:31.817+0000] {processor.py:153} INFO - Started process (PID=1444) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:20:31.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:20:31.823+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:20:31.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:20:31.846+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:20:31.841+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:20:31.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:20:31.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.090 seconds
[2023-01-24T20:21:02.166+0000] {processor.py:153} INFO - Started process (PID=1513) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:21:02.170+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:21:02.172+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:21:02.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:21:02.195+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:21:02.191+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:21:02.197+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:21:02.231+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.076 seconds
[2023-01-24T20:21:32.288+0000] {processor.py:153} INFO - Started process (PID=1577) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:21:32.291+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:21:32.294+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:21:32.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:21:32.317+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:21:32.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:21:32.319+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:21:32.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.072 seconds
[2023-01-24T20:22:02.856+0000] {processor.py:153} INFO - Started process (PID=1641) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:22:02.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:22:02.865+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:22:02.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:22:02.898+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:22:02.891+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:22:02.903+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:22:02.967+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.118 seconds
[2023-01-24T20:22:33.776+0000] {processor.py:153} INFO - Started process (PID=1705) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:22:33.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:22:33.782+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:22:33.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:22:33.810+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:22:33.803+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:22:33.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:22:33.854+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.086 seconds
[2023-01-24T20:23:04.179+0000] {processor.py:153} INFO - Started process (PID=1769) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:23:04.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:23:04.185+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:23:04.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:23:04.203+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:23:04.199+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:23:04.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:23:04.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.079 seconds
[2023-01-24T20:23:34.520+0000] {processor.py:153} INFO - Started process (PID=1843) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:23:34.523+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:23:34.525+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:23:34.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:23:34.544+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:23:34.540+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:23:34.549+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:23:34.580+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.065 seconds
[2023-01-24T20:24:05.265+0000] {processor.py:153} INFO - Started process (PID=1910) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:24:05.269+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:24:05.271+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:24:05.271+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:24:05.289+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:24:05.285+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:24:05.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:24:05.322+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.061 seconds
[2023-01-24T20:24:36.090+0000] {processor.py:153} INFO - Started process (PID=1974) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:24:36.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:24:36.094+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:24:36.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:24:36.112+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:24:36.108+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:24:36.113+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:24:36.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.058 seconds
[2023-01-24T20:25:07.125+0000] {processor.py:153} INFO - Started process (PID=2046) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:25:07.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:25:07.130+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:25:07.130+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:25:07.151+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:25:07.146+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:25:07.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:25:07.183+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.063 seconds
[2023-01-24T20:25:37.626+0000] {processor.py:153} INFO - Started process (PID=2115) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:25:37.629+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:25:37.630+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:25:37.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:25:37.648+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:25:37.644+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:25:37.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:25:37.679+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.057 seconds
[2023-01-24T20:26:08.678+0000] {processor.py:153} INFO - Started process (PID=2180) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:26:08.683+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:26:08.685+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:26:08.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:26:08.712+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:26:08.706+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:26:08.713+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:26:08.746+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.074 seconds
[2023-01-24T20:26:38.863+0000] {processor.py:153} INFO - Started process (PID=2243) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:26:38.867+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:26:38.869+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:26:38.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:26:38.887+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:26:38.884+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:26:38.889+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:26:38.920+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.062 seconds
[2023-01-24T20:27:09.036+0000] {processor.py:153} INFO - Started process (PID=2307) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:27:09.040+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:27:09.042+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:27:09.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:27:09.065+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:27:09.060+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:27:09.067+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:27:09.110+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.080 seconds
[2023-01-24T20:27:39.816+0000] {processor.py:153} INFO - Started process (PID=2384) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:27:39.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:27:39.824+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:27:39.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:27:39.856+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:27:39.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:27:39.858+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:27:39.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.083 seconds
[2023-01-24T20:28:10.475+0000] {processor.py:153} INFO - Started process (PID=2449) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:28:10.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:28:10.480+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:28:10.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:28:10.502+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:28:10.498+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:28:10.504+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:28:10.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.069 seconds
[2023-01-24T20:28:40.937+0000] {processor.py:153} INFO - Started process (PID=2513) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:28:40.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:28:40.942+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:28:40.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:28:40.963+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:28:40.958+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:28:40.965+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:28:41.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T20:29:12.017+0000] {processor.py:153} INFO - Started process (PID=2589) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:29:12.021+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:29:12.024+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:29:12.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:29:12.051+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:29:12.045+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:29:12.054+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:29:12.089+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.079 seconds
[2023-01-24T20:29:42.789+0000] {processor.py:153} INFO - Started process (PID=2653) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:29:42.795+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:29:42.804+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:29:42.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:29:42.847+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:29:42.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:29:42.850+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:29:42.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.119 seconds
[2023-01-24T20:30:13.666+0000] {processor.py:153} INFO - Started process (PID=2717) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:30:13.673+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:30:13.682+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:30:13.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:30:13.732+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:30:13.726+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:30:13.735+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:30:13.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.132 seconds
[2023-01-24T20:30:44.096+0000] {processor.py:153} INFO - Started process (PID=2782) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:30:44.100+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:30:44.102+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:30:44.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:30:44.118+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:30:44.114+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:30:44.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:30:44.148+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.057 seconds
[2023-01-24T20:31:14.878+0000] {processor.py:153} INFO - Started process (PID=2857) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:31:14.883+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:31:14.885+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:31:14.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:31:14.906+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:31:14.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:31:14.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:31:14.955+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.084 seconds
[2023-01-24T20:31:45.898+0000] {processor.py:153} INFO - Started process (PID=2924) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:31:45.902+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:31:45.905+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:31:45.904+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:31:45.926+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:31:45.921+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:31:45.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:31:45.961+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T20:32:16.562+0000] {processor.py:153} INFO - Started process (PID=2988) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:32:16.566+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:32:16.568+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:32:16.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:32:16.588+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:32:16.584+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:32:16.589+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:32:16.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.069 seconds
[2023-01-24T20:32:47.255+0000] {processor.py:153} INFO - Started process (PID=3052) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:32:47.263+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:32:47.269+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:32:47.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:32:47.290+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:32:47.286+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:32:47.292+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:32:47.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.079 seconds
[2023-01-24T20:33:18.124+0000] {processor.py:153} INFO - Started process (PID=3129) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:33:18.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:33:18.130+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:33:18.130+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:33:18.212+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:33:18.146+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:33:18.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:33:18.255+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.137 seconds
[2023-01-24T20:33:48.444+0000] {processor.py:153} INFO - Started process (PID=3193) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:33:48.449+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:33:48.452+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:33:48.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:33:48.472+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:33:48.468+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:33:48.474+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:33:48.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T20:34:19.146+0000] {processor.py:153} INFO - Started process (PID=3259) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:34:19.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:34:19.153+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:34:19.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:34:19.181+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:34:19.174+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:34:19.182+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:34:19.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.094 seconds
[2023-01-24T20:34:49.635+0000] {processor.py:153} INFO - Started process (PID=3323) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:34:49.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:34:49.642+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:34:49.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:34:49.664+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:34:49.659+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:34:49.666+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:34:49.700+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.071 seconds
[2023-01-24T20:35:20.071+0000] {processor.py:153} INFO - Started process (PID=3396) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:35:20.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:35:20.078+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:35:20.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:35:20.110+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:35:20.104+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:35:20.113+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:35:20.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.095 seconds
[2023-01-24T20:35:50.541+0000] {processor.py:153} INFO - Started process (PID=3463) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:35:50.549+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:35:50.551+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:35:50.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:35:50.581+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:35:50.573+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:35:50.583+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:35:50.627+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.095 seconds
[2023-01-24T20:44:04.829+0000] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:44:04.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:44:04.849+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:44:04.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:44:04.915+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:44:04.887+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:44:04.918+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:44:05.040+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.228 seconds
[2023-01-24T20:44:35.858+0000] {processor.py:153} INFO - Started process (PID=107) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:44:35.863+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:44:35.865+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:44:35.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:44:35.996+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:44:35.990+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:44:35.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:44:36.046+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.194 seconds
[2023-01-24T20:45:06.677+0000] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:45:06.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:45:06.684+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:45:06.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:45:08.258+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:45:08.246+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 5, in <module>
    import s3fs
ModuleNotFoundError: No module named 's3fs'
[2023-01-24T20:45:08.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:45:08.305+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 1.633 seconds
[2023-01-24T20:45:38.484+0000] {processor.py:153} INFO - Started process (PID=242) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:45:38.488+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:45:38.490+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:45:38.490+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:45:38.533+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:45:38.528+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:45:38.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:45:38.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.095 seconds
[2023-01-24T20:46:08.682+0000] {processor.py:153} INFO - Started process (PID=304) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:46:08.686+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:46:08.688+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:46:08.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:46:08.712+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:46:08.707+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:46:08.715+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:46:08.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.083 seconds
[2023-01-24T20:46:38.871+0000] {processor.py:153} INFO - Started process (PID=369) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:46:38.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:46:38.877+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:46:38.877+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:46:38.902+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:46:38.897+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:46:38.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:46:38.942+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.077 seconds
[2023-01-24T20:47:09.941+0000] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:47:09.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:47:09.948+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:47:09.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:47:09.972+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:47:09.967+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:47:09.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:47:10.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.121 seconds
[2023-01-24T20:49:58.921+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:49:58.932+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:49:58.935+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:49:58.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:49:59.011+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:49:58.993+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:49:59.014+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:49:59.104+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.210 seconds
[2023-01-24T20:50:29.992+0000] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:50:29.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:50:29.998+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:50:29.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:50:30.019+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:50:30.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:50:30.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:50:30.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T20:51:00.350+0000] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:51:00.353+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:51:00.355+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:51:00.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:51:00.379+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:51:00.373+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:51:00.382+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:51:00.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.078 seconds
[2023-01-24T20:51:31.327+0000] {processor.py:153} INFO - Started process (PID=236) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:51:31.333+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:51:31.335+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:51:31.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:51:31.358+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:51:31.355+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:51:31.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:51:31.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.086 seconds
[2023-01-24T20:52:01.577+0000] {processor.py:153} INFO - Started process (PID=300) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:52:01.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:52:01.582+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:52:01.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:52:01.600+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:52:01.596+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:52:01.601+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:52:01.634+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.063 seconds
[2023-01-24T20:52:31.849+0000] {processor.py:153} INFO - Started process (PID=364) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:52:31.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:52:31.855+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:52:31.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:52:31.876+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:52:31.872+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:52:31.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:52:31.914+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.071 seconds
[2023-01-24T20:53:02.262+0000] {processor.py:153} INFO - Started process (PID=428) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:53:02.266+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:53:02.269+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:53:02.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:53:02.293+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:53:02.287+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:53:02.296+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:53:02.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.087 seconds
[2023-01-24T20:53:32.629+0000] {processor.py:153} INFO - Started process (PID=493) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:53:32.634+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:53:32.636+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:53:32.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:53:32.658+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:53:32.654+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:53:32.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:53:32.695+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.074 seconds
[2023-01-24T20:54:03.468+0000] {processor.py:153} INFO - Started process (PID=567) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:54:03.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:54:03.476+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:54:03.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:54:03.499+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:54:03.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:54:03.501+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:54:03.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.075 seconds
[2023-01-24T20:54:33.891+0000] {processor.py:153} INFO - Started process (PID=636) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:54:33.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:54:33.901+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:54:33.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:54:33.935+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:54:33.926+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:54:33.939+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:54:33.971+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.094 seconds
[2023-01-24T20:55:04.997+0000] {processor.py:153} INFO - Started process (PID=701) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:55:05.000+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:55:05.003+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:55:05.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:55:05.022+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:55:05.018+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:55:05.024+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:55:05.057+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.067 seconds
[2023-01-24T20:55:35.163+0000] {processor.py:153} INFO - Started process (PID=765) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:55:35.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:55:35.168+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:55:35.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:55:35.187+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:55:35.183+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:55:35.188+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:55:35.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.063 seconds
[2023-01-24T20:56:05.399+0000] {processor.py:153} INFO - Started process (PID=829) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:56:05.402+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T20:56:05.404+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:56:05.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:56:05.422+0000] {logging_mixin.py:137} INFO - [2023-01-24T20:56:05.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T20:56:05.425+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T20:56:05.458+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.064 seconds
[2023-01-24T21:56:54.722+0000] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:56:54.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:56:54.731+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:56:54.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:56:54.771+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:56:54.762+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:56:54.773+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:56:54.848+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.135 seconds
[2023-01-24T21:57:24.985+0000] {processor.py:153} INFO - Started process (PID=108) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:57:24.990+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:57:24.993+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:57:24.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:57:25.016+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:57:25.011+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:57:25.018+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:57:25.054+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.074 seconds
[2023-01-24T21:57:55.200+0000] {processor.py:153} INFO - Started process (PID=171) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:57:55.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:57:55.207+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:57:55.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:57:55.232+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:57:55.228+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:57:55.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:57:55.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.084 seconds
[2023-01-24T21:58:25.360+0000] {processor.py:153} INFO - Started process (PID=234) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:58:25.364+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:58:25.366+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:58:25.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:58:25.384+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:58:25.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:58:25.386+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:58:25.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.063 seconds
[2023-01-24T21:58:55.578+0000] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:58:55.583+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:58:55.585+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:58:55.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:58:55.610+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:58:55.603+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:58:55.612+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:58:55.651+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.082 seconds
[2023-01-24T21:59:26.498+0000] {processor.py:153} INFO - Started process (PID=376) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:59:26.501+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:59:26.503+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:59:26.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:59:26.524+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:59:26.520+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:59:26.525+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:59:26.559+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.067 seconds
[2023-01-24T21:59:57.359+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:59:57.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T21:59:57.364+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:59:57.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:59:57.384+0000] {logging_mixin.py:137} INFO - [2023-01-24T21:59:57.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T21:59:57.386+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T21:59:57.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.069 seconds
[2023-01-24T22:00:27.514+0000] {processor.py:153} INFO - Started process (PID=505) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:00:27.518+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:00:27.520+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:00:27.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:00:27.540+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:00:27.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:00:27.541+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:00:27.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.068 seconds
[2023-01-24T22:00:57.720+0000] {processor.py:153} INFO - Started process (PID=569) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:00:57.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:00:57.725+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:00:57.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:00:57.744+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:00:57.740+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:00:57.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:00:57.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.065 seconds
[2023-01-24T22:01:28.555+0000] {processor.py:153} INFO - Started process (PID=632) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:01:28.561+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:01:28.563+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:01:28.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:01:28.598+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:01:28.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:01:28.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:01:28.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.120 seconds
[2023-01-24T22:01:59.116+0000] {processor.py:153} INFO - Started process (PID=696) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:01:59.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:01:59.123+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:01:59.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:01:59.146+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:01:59.142+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:01:59.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:01:59.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.082 seconds
[2023-01-24T22:02:29.458+0000] {processor.py:153} INFO - Started process (PID=760) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:02:29.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:02:29.478+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:02:29.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:02:29.525+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:02:29.515+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:02:29.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:02:29.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.118 seconds
[2023-01-24T22:02:59.838+0000] {processor.py:153} INFO - Started process (PID=826) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:02:59.845+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:02:59.847+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:02:59.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:02:59.887+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:02:59.875+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:02:59.892+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:02:59.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.142 seconds
[2023-01-24T22:08:05.876+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:08:05.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:08:05.898+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:08:05.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:08:05.945+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:08:05.940+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:08:05.947+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:08:05.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.122 seconds
[2023-01-24T22:08:36.025+0000] {processor.py:153} INFO - Started process (PID=109) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:08:36.028+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:08:36.030+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:08:36.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:08:36.051+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:08:36.047+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:08:36.053+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:08:36.090+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.073 seconds
[2023-01-24T22:09:06.192+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:09:06.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:09:06.198+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:09:06.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:09:06.219+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:09:06.215+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:09:06.221+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:09:06.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.070 seconds
[2023-01-24T22:13:26.793+0000] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:13:26.801+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:13:26.803+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:13:26.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:13:26.852+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:13:26.846+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:13:26.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:13:26.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.113 seconds
[2023-01-24T22:13:57.025+0000] {processor.py:153} INFO - Started process (PID=107) to work on /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:13:57.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/twitter_dag.py for tasks to queue
[2023-01-24T22:13:57.032+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:13:57.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:13:57.077+0000] {logging_mixin.py:137} INFO - [2023-01-24T22:13:57.066+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter_dag.py", line 6, in <module>
    from twitter_etl import run_twitter_etl
  File "/opt/airflow/dags/twitter_etl.py", line 1, in <module>
    import tweepy
ModuleNotFoundError: No module named 'tweepy'
[2023-01-24T22:13:57.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter_dag.py
[2023-01-24T22:13:57.130+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/twitter_dag.py took 0.111 seconds
