[2023-01-25T19:05:46.442+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-05-12T00:00:00+00:00 [queued]>
[2023-01-25T19:05:46.485+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-05-12T00:00:00+00:00 [queued]>
[2023-01-25T19:05:46.488+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:05:46.491+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-25T19:05:46.493+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-25T19:05:46.588+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-05-12 00:00:00+00:00
[2023-01-25T19:05:46.608+0000] {standard_task_runner.py:55} INFO - Started process 3403 to run task
[2023-01-25T19:05:46.630+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-05-12T00:00:00+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp_ps6r_ll']
[2023-01-25T19:05:46.633+0000] {standard_task_runner.py:83} INFO - Job 361: Subtask complete_twitter_etl
[2023-01-25T19:05:47.306+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-05-12T00:00:00+00:00 [running]> on host 512d0ff0785b
[2023-01-25T19:05:51.359+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-12T00:00:00+00:00
[2023-01-25T19:05:59.683+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Anonymous access is forbidden for this operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitter_etl.py", line 46, in run_twitter_etl
    df.to_csv("s3://jinchoi-airflow-bucket/data/elonmusk_tweets.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 370, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 428, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in open_files
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 283, in <listcomp>
    [fs.makedirs(parent, exist_ok=True) for parent in parents]
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 883, in _makedirs
    await self._mkdir(path, create_parents=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 868, in _mkdir
    await self._call_s3("create_bucket", **params)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 340, in _call_s3
    method, kwargs=additional_kwargs, retries=self.retries
  File "/home/airflow/.local/lib/python3.7/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
PermissionError: Anonymous access is forbidden for this operation
[2023-01-25T19:05:59.827+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210512T000000, start_date=20230125T190546, end_date=20230125T190559
[2023-01-25T19:05:59.958+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 361 for task complete_twitter_etl (Anonymous access is forbidden for this operation; 3403)
[2023-01-25T19:06:00.316+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-25T19:06:00.488+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-26T07:15:10.751+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-05-12T00:00:00+00:00 [queued]>
[2023-01-26T07:15:10.850+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-05-12T00:00:00+00:00 [queued]>
[2023-01-26T07:15:10.852+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:15:10.864+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-26T07:15:10.866+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T07:15:10.939+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): complete_twitter_etl> on 2021-05-12 00:00:00+00:00
[2023-01-26T07:15:10.953+0000] {standard_task_runner.py:55} INFO - Started process 1545 to run task
[2023-01-26T07:15:10.968+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_dag', 'complete_twitter_etl', 'scheduled__2021-05-12T00:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp5r_nuz88']
[2023-01-26T07:15:10.973+0000] {standard_task_runner.py:83} INFO - Job 224: Subtask complete_twitter_etl
[2023-01-26T07:15:11.908+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_dag.complete_twitter_etl scheduled__2021-05-12T00:00:00+00:00 [running]> on host 2221c1ebf970
[2023-01-26T07:15:12.506+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=complete_twitter_etl
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-12T00:00:00+00:00
[2023-01-26T07:15:15.695+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-26T07:15:16.003+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=twitter_dag, task_id=complete_twitter_etl, execution_date=20210512T000000, start_date=20230126T071510, end_date=20230126T071516
[2023-01-26T07:15:16.491+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-26T07:15:17.603+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
